title: The Year We Met
description: The personal blog of Arturo Herrero & Irene Alegre
url: "http://theyearwemet.com"

markdown: kramdown
permalink: :title

sass:
  style: :compressed
  sass_dir: assets/sass

gems:
  - jekyll-redirect-from

exclude: [Guardfile, .gitignore, README.md]
